run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gofumpt
    - govet
    - gocyclo
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true

  gocyclo:
    min-complexity: 30

  gofumpt:
    extra-rules: true

  revive:
    ignore-generated-header: true
    rules:
      - name: package-comments
        disabled: true

      - name: exported
        disabled: true

      - name: unused-parameter
        disabled: true

      - name: blank-imports
        disabled: true

issues:
  exclude-files:
    - "internal/adapter/graphql/generated.go"
  exclude-rules:
    - path: "internal/adapter/graphql/generated.go"
      linters:
        - gofumpt
        - staticcheck
        - unused
