apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lcp-storage
  labels:
    app: lcp-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lcp-data
  labels:
    app: lcp-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
