apiVersion: v1
kind: Secret
metadata:
  name: readium-core-secret
  labels:
    app: readium-core
type: Opaque
stringData:
  readium-core-user: admin
  readium-core-password: admin_pass
  htpasswd: admin:$apr1$ZzOdyJ/0$vVYymMhp0nb1kYFmlc6wX/
  cert-edrlab-test.pem: |
    -----BEGIN CERTIFICATE-----
    MIIF+DCCA+CgAwIBAgIUDP6eDHt/VNiu/YU0HQMq0/B39a8wDQYJKoZIhvcNAQEL
    BQAwZzELMAkGA1UEBhMCRlIxDjAMBgNVBAcMBVBhcmlzMQ8wDQYDVQQKDAZFRFJM
    YWIxEjAQBgNVBAsMCUxDUCBUZXN0czEjMCEGA1UEAwwaRURSTGFiIFJlYWRpdW0g
    TENQIHRlc3QgQ0EwHhcNMjYwMzIzMTUwMzU0WhcNMzYwMzIwMTUwMzU0WjCBkDEL
    MAkGA1UEBhMCRlIxDjAMBgNVBAcMBVBhcmlzMQ8wDQYDVQQKDAZFRFJMYWIxEjAQ
    BgNVBAsMCUxDUCBUZXN0czEiMCAGA1UEAwwZVGVzdCBwcm92aWRlciBjZXJ0aWZp
    Y2F0ZTEoMCYGCSqGSIb3DQEJARYZbGF1cmVudC5sZW1ldXJAZWRybGFiLm9yZzCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALxK5ueRdpb3iLfaQTpEX57G
    ec43wbP1TFVRj4zr2mn57B0cNMgMluLgRfetPUNE5nLsgYT5MTEA87eZAvEZCYn1
    vAMvCm5i6CiXg+i4PELzOExxQb3LrHGfVdss1hkf1MMr2TRxoy6OSg6i3zhmZGvK
    gbjjz8hi6AJQbLaBxNbsrASweOlZcSP6kudXt4LpR+IgcvyLoUC2Jubp/TYSng6H
    4jcyTzc1iDMwKKWH4fWU1RTDWZWHmigVQc1oUS3/e+q5+xx2fsTTFWU7T6xJAxzG
    zaRF7/TLVdI5dZxVfJM9LEQEQt8IdP9IwElT004003Qca0DOWR5aRq+TlvHcl2P/
    ZyxCsVYlwq6G/03t1XzOj3PpuUh3BwWu9yl9TpoMP83egxzWpEds1S33RynLZsZm
    F27yklgRSRtH/HhqIiNXQDrTfudFNyE4ZEl5ZHeEH1bZH3vlbUG9w4NjnfUyFMAA
    GmGHddWC/RnpYb1eM+iRIuaNCc0Sf9HkZ3OvE/ocu2llLUAhnIX3xjPxAkxguvOn
    0k8v43Ct90SxsjR5a6tuARyOwX0586XKKpisSkU2s7TKGhcTM9iicZBoJwsm4tsy
    WFcFcVFbELH6uR2FexxsD9DQJyJn6n3kYQXYLLoy1zAIHMgb1XNAxxrYv6i2htzS
    AkPzDBefCAAoj2krvoStAgMBAAGjcjBwMAwGA1UdEwEB/wQCMAAwCwYDVR0PBAQD
    AgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQWBBQZ40AVcciIYjNMQSMi
    kYE8UZoA5TAfBgNVHSMEGDAWgBT6EPXzvkI7xQ5AT88XBHt5fPjlSzANBgkqhkiG
    9w0BAQsFAAOCAgEAO3ffTWg9FXpdhErUaPBgyvbppK7FCZE4Gta71Y5TM7EX5AhC
    Cwj18X0VxIjYyMivYjH4uWSdV8rlp/zru7L7Ioxw/Lzt5u5DyG6yfy6F+NzRXWPr
    LoLV4uGRwUyn/KmoRoirPEc0e2DPoHrL7MwvnpGvMOc8Ox6kjb9zLLoEG3jbNYtv
    TpwBb9O09bW7F4b7CEKqfhP4bto4Qy2OnStm5AnGcjPCUl2spsjsX4aBbtu7u4fp
    ac/C5sA5EKX2QAAWkSNGRPMtPoL15TmkR6Xz7lZGNKy9G/bkIIN9Jn3u/bz5Mk3h
    ISw2IY8ikyvgAzLwsgVKn+PX69po+aH4BKcgqxiGGjUVFX9mZiSDynuOs9ViR8ls
    E3PPnTWG+EMwhpZkoo/b81YvyfU4j1dW60J9bWYjPkg6kQForFqSOAEgEKA60MP0
    gdm+lfz9avzZW7q3PjQGtLroPl7QqFm14gY9CUUEKJ06W4HlI5LpdBNmgJptN/90
    bOruATV6vORZdvcY84JjzY+fzdkkYpNRrxgLngglP0nTsQtzLMUkCPJDvQp/RHbf
    WArTAQ38KRfTv9AUbKNnuMe++XH/edaHrVUWiQ/IuqeG7v9X4f/HpL0ZFsdjz8eo
    katWP97P9XTLR5N2fCUaoXoFve0D4H3OaSdAmluw6vDqEprVwsIHRUCdfRY=
    -----END CERTIFICATE-----
  privkey-edrlab-test.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQC8SubnkXaW94i3
    2kE6RF+exnnON8Gz9UxVUY+M69pp+ewdHDTIDJbi4EX3rT1DROZy7IGE+TExAPO3
    mQLxGQmJ9bwDLwpuYugol4PouDxC8zhMcUG9y6xxn1XbLNYZH9TDK9k0caMujkoO
    ot84ZmRryoG448/IYugCUGy2gcTW7KwEsHjpWXEj+pLnV7eC6UfiIHL8i6FAtibm
    6f02Ep4Oh+I3Mk83NYgzMCilh+H1lNUUw1mVh5ooFUHNaFEt/3vqufscdn7E0xVl
    O0+sSQMcxs2kRe/0y1XSOXWcVXyTPSxEBELfCHT/SMBJU9NONNN0HGtAzlkeWkav
    k5bx3Jdj/2csQrFWJcKuhv9N7dV8zo9z6blIdwcFrvcpfU6aDD/N3oMc1qRHbNUt
    90cpy2bGZhdu8pJYEUkbR/x4aiIjV0A6037nRTchOGRJeWR3hB9W2R975W1BvcOD
    Y531MhTAABphh3XVgv0Z6WG9XjPokSLmjQnNEn/R5GdzrxP6HLtpZS1AIZyF98Yz
    8QJMYLrzp9JPL+NwrfdEsbI0eWurbgEcjsF9OfOlyiqYrEpFNrO0yhoXEzPYonGQ
    aCcLJuLbMlhXBXFRWxCx+rkdhXscbA/Q0CciZ+p95GEF2Cy6MtcwCBzIG9VzQMca
    2L+otobc0gJD8wwXnwgAKI9pK76ErQIDAQABAoICABSPp1RNLaKBqFPPSQUoVzq6
    2K08qHHSzQGaFO9iB+k/qdlp7ZeUzFs8+1b2+3Qfj3yoN+KB5a3AuVxooIocXk7K
    3zuHxP9V3J0mInjkuWvkLFconPGxToTfzdvPsxduQukHHkJcUGHylsKvZWm+wKOG
    qxC6C8QJjOVHy/9H/2sq0AP5E1MD+ddgcu9BRGBOwhM+0N+kDblHysq3bXeco9bZ
    XsoBO+Y++b8BOMcOpg2PsY8BYAR0mNBcteFMzWSU+/6fTX0HsYMju7fguKwLEwRu
    7yDLpE7ab2Yz8RRfv2lCqlVJE9ZQEZqY4qp/NVlaambI/atHfTLTz9k3aCnEGWHZ
    Z0qa1sMvfBlNwgIBUXuNzHO4UMCsQTinZ5AByFL4uVRGWG6KEEAaFgv77VoW13yh
    BGQWtVyJKmEbqyI9BQSF9KYJuAfdhdWKluZ8NzIweB60dTT8nNuc4BU49tZm48PZ
    BpkMVe/A0IQKsJ1Hh4c8Nl1ARajhKafaCK7XZmTc7lNL1J6pFLqWM/mj3Tl0j23M
    mUXedYcaBtdw7SyFeFobnQW1xf1N9kprUuk+HL7jpxu1EaH/EEb0R1+a+WFJO9YC
    fv45zkvbSPiT7xV5s49pGuJohgt6h+rPALTdzwkfU6OcbeSxI99C68Rc22EYwFr6
    0nh7RI793zLUoUKeqMIfAoIBAQDw7NYDFH9hrx9U08DcYrK4sGFrFrpckzv9o741
    uSJXhn1kphBO8w0OVBU9ytP7AZjK0TwdHNwBJIKc7Llg2oTBxBHj9xyLphsPsTU4
    VJwZuxKxsUmAA/tk2FFtWMRgYxwT/4lX7Up6fU5paHzNI7tMhvz1DCpVGF0KWNea
    Szl2RcdzhBN/1w9WXv90+rNDrfHjYD1qHG9LdVr3t3zl3Zp0tAPxOOROKsvIaDbz
    sWjQYOytb7gkKnDDeRSgbwEfGYEEEOtAstkGZ2zNdjfh1FMbtITEMg/Es9Yhl51d
    VuHq2H80uNSLa7WXVqxe2T1H5uajG6ti7zKmh2cxGY+IeAczAoIBAQDIEv4DUwFc
    dB1blSO+oyzXSeLEA99SmYe+O0/m5ijPTzKeSh7z35UJzzy/YED87aFYfN8tnrh6
    /vj/5zz3BuzDjYJnxkOdA3kmVzb7+vhHBTJfapFpgzypqpH0HzAmMtI8d8bSJuaw
    a3IrsKMF5n5M1TzmrHtzdnrj8lrCVwZktFUMFMszWR91FG9aP4iYPBZjhQeRwEvJ
    tfZBPu+AEFyh1bJVZJKOL0CT+2rS+qkf6CtRgYj+hB6uHNl9UHiK/h/qK2v0X4tJ
    aszF0lzR/hC1T8cxqY8H5YfouNm7fwL2NiOYwrA5BUMCGSgJjOurPd4RFjujMhRx
    NQE2IQthlcSfAoIBAQCD+IemekTogl/8PF4JmrrhdiR236VH7pLO9jHMBdRs80ue
    pWSLipGdRqu4BHGnrhE/D+wI2nUc3x34zaciCbDs3vUZ1ZO6X0u1hdFsQNSdN58e
    3MkxKX08mU3JQvWXAtMvlStrkZzZieg4zzaFvEvtuIe5x2cs48KbV10KtKgORFzj
    xvZTcb+CBVmTf3xQ12iHr4EUrey8/dTNmqH83C2uPalnKk3ND54+8e8gAA81DdK3
    klng3aqVOK72zrdjjLniO05SS2WcH203AsnLl13K8FBFlFKU4hmqnv1hUqU/2kWb
    4J70nBSFiMG01vS9fRrbP93avMIW/FanS6QXEgCHAoIBAQC7/OxjHzjmL8vt40IE
    u7lESA4j8yeAqvVajsxSveuWbmm3RRm0N14IK4p+nugxPu4dAKeKa9oW5z/64sDr
    srwAOhRPgYDCJSNOHSByvqtNv9pGwREEPOVg3f3pjOxm19WmLzzG9PpIxYwu9PcY
    ciw18R4Z9/K+2JI7X9pbQ/2j3bUTdu4+vvzJu3utJokn0T2QIMyt7CrJyokpYQMU
    J0uCXBIGHkt+AXQCF3eV6SPD8RfSq42W53kUS9Mm5dd9ca13D3mN0cBEKW9iaHgC
    b2AvnFgjl5fm6Yo75oPeokacJN5piHSf/wupCw4NezVsXuMq1uMOQd3nSNBslbvl
    4x0tAoIBAQCY1Sjy2G6uhwKFdeVFXFCq4MbqH2Jt6AGiIWcz/M+hVEIwuuVc35Mx
    DC2IDrk3/h5XsbYH+uW6RwGOcFrhXwjB2FO+nYoeqxrVHAgYARJUlbmATqhHWllY
    mYOYce+zOYbPYEA/zF6RvVejpB1ffbuymByS/wHXg565EMWhwu0PmNXBdoSmy2Ks
    F2sIw2XR8pB78I6sBLOjgMuCFkkukTAIXH37URM23V9gy/3HSz9kV/VPoT9Y4nl3
    7e93zOeq5Ar2RYdymURuS0VPMLNLucNna0aDIqAMzsXjJj0Mw8655+nHAPDM8nBy
    dYFuWekmU2p7NQxSapJSHO/QoWDpRQgR
    -----END PRIVATE KEY-----
