apiVersion: v1
kind: Service
metadata:
  name: lcp-redis
  labels:
    app: lcp-redis
spec:
  selector:
    app: lcp-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lcp-redis
  labels:
    app: lcp-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lcp-redis
  template:
    metadata:
      labels:
        app: lcp-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
