apiVersion: v1
kind: ConfigMap
metadata:
  name: lcp-config
data:
  LCP_PROFILE: development
  PUBLIC_BASE_URL: https://dev.testmedical.ir
  LCP_PROVIDER_URI: https://dev.testmedical.ir
  STATUS_BASE_URL: https://status.testmedical.ir
